[package]
name = "guardian-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
casper-types = { workspace = true, default-features = false }

[features]
default = []
std = []
